name: Deploy to firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Setup the code
        run: npm install
      - name: Test the code
        run: npm test
      - name: Deploy to Firebase
        uses: mohammed-atif/firebase-publish-react@v1.0
        with:
          firebase-token: ${{ secrets.FIREBASE_TOKEN }}
